// ./dataLayer
export { default as clickedAskQuestion } from '@/helpers/dataLayer/clickedAskQuestion'
export { default as clickedGetFullStudyPlan } from '@/helpers/dataLayer/clickedGetFullStudyPlan'
export { default as clickedGetFullTeachersList } from '@/helpers/dataLayer/clickedGetFullTeachersList'
export { default as filledUpFormWithoutSubmission } from '@/helpers/dataLayer/filledUpFormWithoutSubmission'
export { default as openedMainForm } from '@/helpers/dataLayer/openedMainForm'

// ./general
export { default as checkIfResourceExists } from '@/helpers/general/checkIfResourceExists'
export { default as createBlended } from '@/helpers/general/createBlended'
export { default as createLeadBackApi } from '@/helpers/general/createLeadBackApi'
export { default as createProgramModules } from '@/helpers/general/createProgramModules'
export { default as createProgramModulesBase } from '@/helpers/general/createProgramModulesBase'
export { default as createProgramModulesSpecialized } from '@/helpers/general/createProgramModulesSpecialized'
export { default as createSmartParagraph } from '@/helpers/general/createSmartParagraph'
export { default as getClassNames } from '@/helpers/general/getClassNames'
export { default as getImageHeight } from '@/helpers/general/getImageHeight'
export { default as handlePlaceholder } from '@/helpers/general/handlePlaceholder'
export { default as hitContactRoute } from '@/helpers/general/hitContactRoute'
export { default as hitMaterialsRoute } from '@/helpers/general/hitMaterialsRoute'
export { default as getBackJWTToken } from '@/helpers/general/getBackJWTToken'
export { default as onSubmitForm } from '@/helpers/general/onSubmitForm'
export { default as onSubmitFormArticle } from '@/helpers/general/onSubmitFormArticle'
export { default as toNumberWithSpaces } from '@/helpers/general/toNumberWithSpaces'
export { default as getRenderTime } from '@/helpers/general/getRenderTime'
export { default as handleSubmitFormArticle } from '@/helpers/general/handleSubmitFormArticle'
export { default as formatDate } from '@/helpers/general/formatDate'

// ./ruCases
export { default as ruCaseMonth } from '@/helpers/ruCases/ruCaseMonth'
export { default as ruCaseProgram } from '@/helpers/ruCases/ruCaseProgram'
export { default as ruCaseHours } from '@/helpers/ruCases/ruCaseHours'
export { default as ruCaseSubjects } from '@/helpers/ruCases/ruCaseSubjects'
