type TypeLibTypename =
	// | 'ComponentJournalParagraph'
	// | 'ComponentJournalTitle'
	// | 'ComponentGeneralPicture'
	// | 'ComponentJournalEmphasis'
	// | 'ComponentJournalFormPdfMaterials'
	// | 'ComponentJournalJournalTable'
	// | 'ComponentJournalQuote'
	// | 'ComponentJournalJournalRecommendedArticles'
	// | 'ComponentJournalJournalRecommendedProgram'
	// | 'ComponentJournalList'
	// | 'ComponentJournalConclusion'
	// | 'ComponentJournalJournalArticleRecommendedProgramsSection'
	// | 'ComponentJournalReadAlsoArticles'
	| 'journal.paragraph'
	| 'journal.title'
	| 'general.picture'
	| 'journal.emphasis'
	| 'journal.form-pdf-materials'
	| 'journal.journal-table'
	| 'journal.quote'
	| 'journal.journal-recommended-articles'
	| 'journal.journal-recommended-program'
	| 'journal.list'
	| 'journal.conclusion'
	| 'journal.journal-article-recommended-programs-section'
	| 'journal.read-also-articles'

export default TypeLibTypename
