// ./
export { default as PopupForm } from '@/components/popups/PopupForm'
export { default as PopupImage } from '@/components/popups/PopupImage'
export { default as PopupInfo } from '@/components/popups/PopupInfo'
export { default as PopupDuration } from '@/components/popups/PopupDuration'
export { default as PopupLearnMore } from '@/components/popups/PopupLearnMore'
export { default as PopupLoader } from '@/components/popups/PopupLoader'
export { default as PopupReview } from '@/components/popups/PopupReview'
export { default as PopupTeacher } from '@/components/popups/PopupTeacher'
export { default as PopupThankyou } from '@/components/popups/PopupThankyou'
export { default as PopupToShare } from '@/components/popups/PopupToShare'
export { default as PopupCoursesOnTopic } from '@/components/popups/PopupCoursesOnTopic'
export { default as PopupDownloadMaterials } from '@/components/popups/PopupDownloadMaterials'
export { default as PopupPreviewCoursesOnTopic } from '@/components/popups/PopupPreviewCoursesOnTopic'
export { default as PopupGetMaterials } from '@/components/popups/PopupGetMaterials'
