// ./
export { default as BlendedProgram } from '@/components/pages/BlendedProgram'
export { default as CourseOnlineProgram } from '@/components/pages/CourseOnlineProgram'
export { default as InternationalBusinessLaw } from '@/components/pages/InternationalBusinessLaw'
export { default as OnlineProgram } from '@/components/pages/OnlineProgram/OnlineProgram'
export { default as PageJournalArticles } from '@/components/pages/PageJournalArticles'
export { default as ProfessionOnlineProgram } from '@/components/pages/ProfessionOnlineProgram/ProfessionOnlineProgram'
export { default as Programs } from '@/components/pages/Programs'
export { default as Webinars } from '@/components/pages/Webinars'
export { default as Reviews } from '@/components/pages/Reviews/Reviews'
